[package]
distribution = "2201.9.2"
org = "ballerinax"
name = "openai.chat"
version = "2.0.1"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [] # TODO: Add keywords
icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/module-ballerinax-openai.chat"

[build-options]
observabilityIncluded = true